---
# - name: Get disk facts # usefull only for debug
  # community.windows.win_disk_facts:
  # register: _diskfacts

# - name:
#   debug: var=_diskfacts

- name: Get disk drive
  set_fact:
    _disk: "{{ _disk | default ([]) | combine(item.1.drive_letter) | list }}"
  loop: "{{ ansible_facts.disks | subelements('partitions') }}"

# - name: print disks
#   debug: var=_disk